### ISSUE TITLE
Live url is not responding

### ISSUE THREAD

**Issue by serkanatpaystack** [franklinekoh/starwars#1]
There seems to be a problem with the live demo url

http://unthankful-indicato.000webhostapp.com/ seems to be unreachable

**Comment by serkanatpaystack** [comment]
@franklinekoh I saw your screenshot. Is it a live network request or is it perhaps a browser cache?

Did you try curling the url or checking the network tab of your browser console?

**Comment by franklinekoh** [comment]
it works fine from my end. 
![working](https://user-images.githubusercontent.com/30264870/56886508-10f24780-6a67-11e9-944a-dc434006a944.PNG)

**Comment by franklinekoh** [comment]
Could it be from your browser cache? can I see a screen shot?
![Capture](https://user-images.githubusercontent.com/30264870/56886913-03898d00-6a68-11e9-99e8-578b659beb55.PNG)

**Comment by serkanatpaystack** [comment]
![image](https://user-images.githubusercontent.com/44980164/56887559-9af7db80-6a7a-11e9-940e-444662ac4b73.png)

This is not just the browser, I cannot get a response with postman or cURL either.

**Comment by franklinekoh** [comment]
Please refer to https://github.com/franklinekoh/starwarsNodejs.  I will add a live url soon
