### ISSUE TITLE
Codebase organization

### ISSUE THREAD

**Issue by serkanatpaystack** [franklinekoh/starwars#4]
Although unnecessary, it is still fine to use a framework to bootstrap an application.

But in which case a developer is generally expected to clean up the boilerplate and unused cruft, noisy comments, extra files etc so that it becomes easy to focus on what matters.

Furthermore, the existing code organization does not immediately make it easy to understand where to begin from and where to look.

Laravel provides some basic out of box defaults for organization. But it also provides configuration options to change some of these defaults. For instance, the app directory houses two models. app is just an arbitrary directory name and its immediately containing a model does not help the codebase scale better.

Furthermore, separation of the codebase within technical boundaries such as models, controllers etc is a construct of small applications that are not assumed to scale. It is usually considered better practice to separate the app codebase into contextual modules/directories where the context represents the app's feature.

**Comment by franklinekoh** [comment]
@serkanatpaystack. I wrote the program again in node. although incomplete and as a pet project. I believe the code base is well organized. However, I know it can be improved  Please refer to https://github.com/franklinekoh/starwarsNodejs for the nodejs version where this has been completed. Thank you

**Comment by serkanatpaystack** [comment]
Hi there, this is quite a pleasant surprise to see that you want to pursue
this.

I am currently overwhelmed with some work but I will definitely take a look
and provide feedback.

**Comment by franklinekoh** [comment]
Hi Serkan,

That will be very helpful. Thanks.

Regards,
Ekoh Franklin
