### ISSUE TITLE
API is incomplete

### ISSUE THREAD

**Issue by serkanatpaystack** [franklinekoh/starwars#7]
The api is not complete compared to the spec.

There is no way to get comments for a given movie or characters for a given movie.

Furthermore, all comments and all characters were not requested per the spec.

Finally, the all comments endpoint does not make an effort to limit response body, nor does the characters endpoint follow the swapi api paging, therefure returning only the first page.

**Comment by franklinekoh** [comment]
@serkanatpaystack Please refer to https://github.com/franklinekoh/starwarsNodejs for the nodejs version where this has been completed. Thank you
